package com.smartisan.weather.util

import com.smartisan.weather.R
import com.smartisan.weather.custom.WeatherResId

/** Weather presentation adapters and the original administrative-area abbreviations. */
object ResMappingUtil {
    private val unknownWeatherIcon = WeatherResId(
        R.drawable.little_icon_unknown, R.drawable.little_icon_unknown,
        R.drawable.little_icon_unknown_shadow, -1,
    )

    private val weatherIcons = WeatherCodeMapping.textResMap.keys.associateWith { code ->
        val icons = WeatherCodeMapping.getIconSet(code)
        WeatherResId(icons.dayIcon, icons.nightIcon, icons.shadowIcon, icons.nightShadowIcon)
    }

    private val cityAbbreviations = mapOf(
        "内蒙古自治区" to "内蒙古",
        "新疆维吾尔自治区" to "新疆",
        "西藏自治区" to "西藏",
        "宁夏回族自治区" to "宁夏",
        "广西壮族自治区" to "广西",
        "大兴安岭地区" to "大兴安岭",
        "延边朝鲜族自治州" to "延边",
        "锡林郭勒盟" to "锡林郭勒",
        "昌吉回族自治州" to "昌吉",
        "伊犁哈萨克自治州" to "伊犁",
        "吐鲁番地区" to "吐鲁番",
        "巴音郭楞蒙古自治州" to "巴音郭楞",
        "阿克苏地区" to "阿克苏",
        "喀什地区" to "喀什",
        "塔城地区" to "塔城",
        "哈密地区" to "哈密",
        "和田地区" to "和田",
        "阿勒泰地区" to "阿勒泰",
        "克孜勒苏柯尔克孜自治州" to "克州",
        "博尔塔拉蒙古自治州" to "博尔塔拉",
        "日喀则地区" to "日喀则",
        "山南地区" to "山南",
        "林芝地区" to "林芝",
        "昌都地区" to "昌都",
        "那曲地区" to "那曲",
        "阿里地区" to "阿里",
        "黄南藏族自治州" to "黄南",
        "海南藏族自治州" to "海南",
        "果洛藏族自治州" to "果洛",
        "玉树藏族自治州" to "玉树",
        "海西蒙古族藏族自治州" to "海西",
        "海北藏族自治州" to "海北",
        "临夏回族自治州" to "临夏",
        "甘南藏族自治州" to "甘南",
        "恩施土家族苗族自治州" to "恩施",
        "神农架林区" to "神农架",
        "湘西土家族苗族自治州" to "湘西",
        "黔南布依族苗族自治州" to "黔南",
        "黔东南苗族侗族自治州" to "黔东南",
        "黔西南布依族苗族自治州" to "黔西南",
        "凉山彝族自治州" to "凉山",
        "甘孜藏族自治州" to "甘孜",
        "阿坝藏族羌族自治州" to "阿坝",
        "大理白族自治州" to "大理",
        "红河哈尼族彝族自治州" to "红河",
        "文山壮族苗族自治州" to "文山",
        "楚雄彝族自治州" to "楚雄",
        "怒江傈僳族自治州" to "怒江",
        "迪庆藏族自治州" to "迪庆",
        "德宏傣族景颇族自治州" to "德宏",
        "西双版纳傣族自治州" to "西双版纳",
        "威宁彝族回族苗族自治县" to "威宁",
        "昌江黎族自治县" to "昌江",
        "白沙黎族自治县" to "白沙",
        "琼中黎族苗族自治县" to "琼中",
        "保亭黎族苗族自治县" to "保亭",
        "陵水黎族自治县" to "陵水",
        "乐东黎族自治县" to "乐东",
        "察布查尔锡伯自治县" to "察布查尔",
        "焉耆回族自治县" to "焉耆",
        "和布克赛尔蒙古自治县" to "和布克赛尔",
        "巴里坤哈萨克自治县" to "巴里坤",
        "河南蒙古族自治县" to "河南",
        "积石山保安族东乡族撒拉族自治县" to "积石山",
        "东乡族自治县" to "东乡",
        "三都水族自治县" to "三都",
        "木里藏族自治县" to "木里",
        "漾濞彝族自治县" to "漾濞",
        "巍山彝族回族自治县" to "巍山",
        "南涧彝族自治县" to "南涧",
        "屏边苗族自治县" to "屏边",
        "金平苗族瑶族傣族自治县" to "金平",
        "河口瑶族自治县" to "河口",
        "兰坪白族普米族自治县" to "兰坪",
        "贡山独龙族怒族自治县" to "贡山",
        "维西傈僳族自治县" to "维西",
        "融水苗族自治县" to "融水",
        "金秀瑶族自治县" to "金秀",
        "龙胜各族自治县" to "龙胜",
        "恭城瑶族自治县" to "恭城",
        "富川瑶族自治县" to "富川",
        "隆林各族自治县" to "隆林",
        "巴马瑶族自治县" to "巴马",
        "环江毛南族自治县" to "环江",
        "罗城仫佬族自治县" to "罗城",
        "都安瑶族自治县" to "都安",
        "大化瑶族自治县" to "大化",
        "道真仡佬族苗族自治县" to "道真",
        "丰宁满族自治县" to "丰宁",
        "围场满族蒙古族自治县" to "围场",
        "土默特右旗" to "土右旗",
        "土默特左旗" to "土左旗",
        "达尔罕茂明安联合旗" to "达茂旗",
        "察哈尔右翼前旗" to "察右前旗",
        "察哈尔右翼中旗" to "察右中旗",
        "察哈尔右翼后旗" to "察右后旗",
        "科尔沁左翼中旗" to "科左中旗",
        "科尔沁左翼后旗" to "科左后旗",
        "奈曼旗" to "奈曼",
        "扎鲁特旗" to "扎鲁特",
        "阿鲁科尔沁旗" to "阿鲁旗",
        "克什克腾旗" to "克什克腾",
        "翁牛特旗" to "翁牛特",
        "敖汉旗" to "敖汉",
        "达拉特旗" to "达拉特",
        "准格尔旗" to "准格尔",
        "鄂托克前旗" to "鄂前旗",
        "伊金霍洛旗" to "伊金霍洛",
        "乌拉特前旗" to "乌前旗",
        "乌拉特中旗" to "乌中旗",
        "乌拉特后旗" to "乌后旗",
        "阿巴嘎旗" to "阿巴嘎",
        "苏尼特左旗" to "苏左旗",
        "苏尼特右旗" to "苏右旗",
        "东乌珠穆沁旗" to "东乌旗",
        "西乌珠穆沁旗" to "西乌旗",
        "正蓝旗" to "正兰旗",
        "莫力达瓦达斡尔族自治旗" to "莫力达瓦",
        "鄂伦春自治旗" to "鄂伦春旗",
        "鄂温克族自治旗" to "鄂温克旗",
        "陈巴尔虎旗" to "陈旗",
        "新巴尔虎左旗" to "新左旗",
        "新巴尔虎右旗" to "新右旗",
        "科尔沁右翼中旗" to "科右中旗",
        "科尔沁右翼前旗" to "科右前旗",
        "阿拉善左旗" to "阿左旗",
        "阿拉善右旗" to "阿右旗",
        "额济纳旗" to "额济纳",
        "扎赉特旗" to "扎赉特",
        "六枝特区" to "六枝",
        "香港特别行政区" to "香港",
        "香港特別行政區" to "香港",
        "九龙城区" to "九龙",
        "九龍城區" to "九龙",
        "觀塘區" to "九龙",
        "深水埗區" to "九龙",
        "黃大仙區" to "九龙",
        "油尖旺區" to "九龙",
        "離島區" to "新界",
        "葵青區" to "新界",
        "北區" to "新界",
        "西貢區" to "新界",
        "沙田區" to "新界",
        "大埔區" to "新界",
        "荃灣區" to "新界",
        "屯門區" to "新界",
        "元朗區" to "新界",
        "中西區" to "香港",
        "東區" to "香港",
        "南區" to "香港",
        "灣仔區" to "香港",
    )

    fun getCitySimpleName(str: String?): String? = cityAbbreviations[str] ?: str

    fun getWeatherResId(str: String?): WeatherResId = weatherIcons[str] ?: unknownWeatherIcon

    fun getWindDirRedId(str: String?): Int = WeatherCodeMapping.windDirResMap[str] ?: R.string.weather_null

    fun isUnknown(str: String?): Boolean = WeatherCodeMapping.isUnknown(str)
}
